mtk: misc: Fix a declaration prototype is deprecated
../drivers/misc/mediatek/connectivity/common/common_detect/drv_init/wlan_drv_init.c:23:49: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int __attribute__((weak)) mtk_wcn_wlan_gen4_init()
                                                ^
                                                 void
../drivers/misc/mediatek/connectivity/common/common_detect/drv_init/wlan_drv_init.c:29:49: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int __attribute__((weak)) mtk_wcn_wlan_gen3_init()
                                                ^
                                                 void
../drivers/misc/mediatek/connectivity/common/common_detect/drv_init/wlan_drv_init.c:35:49: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int __attribute__((weak)) mtk_wcn_wlan_gen2_init()
                                                ^
                                                 void
../drivers/misc/mediatek/connectivity/common/common_detect/drv_init/wlan_drv_init.c:41:48: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
int __attribute__((weak)) mtk_wcn_wmt_wifi_init()
                                               ^
                                                void
4 errors generated.

Signed-off-by: Masalief Maulana <masaliefmaulana@proton.me>
Tested-by: Masalief Maulana <masaliefmaulana@proton.me>