mtk: misc: Fix a function declaration is deprecated
../drivers/misc/mediatek/connectivity/common/common_main/platform/mtk_wcn_consys_hw.c:790:43: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct pinctrl *mtk_wcn_consys_get_pinctrl()
                                          ^
                                           void
1 error generated.

Signed-off-by: Masalief Maulana <masaliefmaulana@proton.me>
Tested-by: Masalief Maulana <masaliefmaulana@proton.me>